### ISSUE TITLE
Better support for compiler plugins

### ISSUE THREAD

**Issue by tschuchortdev** [tschuchortdev/kotlin-compile-testing#15]
It should already be possible to test compiler plugins by adding their path to the `pluginClasspath`. However, this is kinda annoying as you have to find that path first (which may or may not necessitate writing a Jar with the service registrations manually) and the `ComponentRegistrar`s will be instantiated by the compiler's service locator, so we can't pass any arguments to it or use anonymous classes in tests. Since we are already doing all this with the custom `KaptComponentRegistrar`, I figure we could just execute a list of given `ComponentRegistrar`s there. Care has to be taken to ensure that only the right `ComponentRegistrar`s are executed during the right compilation stages (maybe use separate `ComponentRegistrar`s or a thread-local flag if nothing else works). 

Any thoughts on this?

@Foso

**Comment by Foso** [comment]
@tschuchortdev I don't know (yet) what the best solution is. But i wanted to let you know that i was able to pass my ComponentRegistrar for my library MpApt and got it executed from inside a test.

https://github.com/Foso/kotlin-compile-testing/commit/a548cc08030dcb8743abc852366082883692d0c6

I added a list of ComponentRegistrars to the Parameters class. Then inside the  KaptComponentRegistrar i iterated over the list and executed my ComponentRegistrar by calling the registerProjectComponents() function.


Maybe we need to add something like a "MainComponentRegistrar"-class and start the KaptComponentRegistrar or the added ComponentRegistrars from there.

**Comment by tschuchortdev** [comment]
Nice, then we know that this approach can work in theory at least. 

> Maybe we need to add something like a "MainComponentRegistrar"-class and start the KaptComponentRegistrar or the added ComponentRegistrars from there.

My intuition is that we will probably need two separate `ComponentRegistrars`: One for kapt to register the user's annotation processors and one to register the user's compiler plugins. This could be problematic because we can only give the classpath to `K2JVMCompiler` which will always contain both, so another hacky solution with "global" variables may be necessary to "activate" only one of them depending on the compilation phase. Or maybe we are lucky and it doesn't matter if we execute the compiler plugins in the kapt phase. But I suspect that there are some hidden problems here, for example Kotlin sources generated during the kapt phase not being seen by the compiler plugins (kapt doesn't even support multi-round processing). So you should definitely test what difference it makes in which compiler phases the compiler plugins are executed.

**Comment by tschuchortdev** [comment]
Resolved with #27 and 5b95782
