### ISSUE TITLE
Please clarify the status of the project

### ISSUE THREAD

**Issue by alexander-yevsyukov** [tschuchortdev/kotlin-compile-testing#199]
As the badge in the [README file](https://github.com/tschuchortdev/kotlin-compile-testing#readme) tells us, the project is [not maintained since 2020](https://camo.githubusercontent.com/37e69af2ba928d83d37adcd44a0ec15a76322386e6f3d6275d80d79c4c5bfe22/68747470733a2f2f696d672e736869656c64732e696f2f6d61696e74656e616e63652f7965732f323032302e7376673f7374796c653d706f706f7574). 

The [history of releases](https://github.com/tschuchortdev/kotlin-compile-testing/releases) looks quite opposite: there were 8 releases this year, with the latest one (1.4.4.) 6 days ago.

It would be good to clarify the status of the library to those who consider using it.

**Comment by tschuchortdev** [comment]
The project is still being maintained. I don't know why the badge is like that, afaik it should look at time since last release or commit. I should probably remove it.
