### ISSUE TITLE
Publish on maven central / jcenter

### ISSUE THREAD

**Issue by stephanenicolas** [tschuchortdev/kotlin-compile-testing#2]
Hi @tschuchortdev , your lib is only available via jitpack which makes it hard to use for a production lib/app. Do you mind to publish it on central ?

**Comment by tschuchortdev** [comment]
Hi, 
I did not realize that jitpack was an inconvenience. I will look into publishing it on maven central, however I am very busy right now so it might take a week or two (I don't know yet how much work it will be). 

If you know of any good tutorial how to publish on maven central, feel free to leave it as a comment.

**Comment by malvinstn** [comment]
Maybe this can help: https://medium.com/@nmauti/sign-and-publish-on-maven-central-a-project-with-the-new-maven-publish-gradle-plugin-22a72a4bfd4b

**Comment by raulraja** [comment]
Also would love to see this in central, thanks for this awesome lib.

**Comment by tschuchortdev** [comment]
The library should be on maven central now. 
May I ask why you prefer maven central to jitpack? What about jcenter? Because publishing on central is a lot more complicated than on jitpack, for little apparent benefit.

**Comment by ZacSweers** [comment]
- central artifacts can't be deleted
- the setup is a one time cost, and zero overhead to upload to after that
- jitpack requires manual configuration from all consumers, often who don't
know what jitpack is
- sonatype has relatively strong protections around groupId ownership and
access, which means better security for consumers

A lot of it boils down to meeting the community where it is

**Comment by tschuchortdev** [comment]
@ZacSweers Alright, what do you think about jcenter? As I've heard, it is supposedly faster and has a less asinine user interface than sonatype nexus.

**Comment by ZacSweers** [comment]
Jcenter has most of the same problems regarding artifact deletion and lack
of group id protections. They've also had several very public incidents
(search "Jake whaarton"), outages, and frankly have some monstrously
unprofessional devrel folks. There's a very strong reason Google moved to
their own maven repo, and Kotlin really only uses it as a mirror or for the
kotlinx custom repo they control (and is intentionally opt-in).

The sonatype UI is old, sure. But you only have to use it for 10 seconds
and it generally Just Works.

**Comment by raulraja** [comment]
Jcenter can sync automatically with central if you just use bintray OSS and
they will sign the packages for you. This is how arrow does it.

**Comment by ZacSweers** [comment]
As a consumer I'd be fine with that if that's easier for the maintainer.
That said, I still wouldn't recommend jcenter being the primary source :)

**Comment by tschuchortdev** [comment]
I'll leave it on maven central for now since that seems to be working, but will consider jcenter for the future. Hopefully [this](https://github.com/vanniktech/gradle-maven-publish-plugin/pull/63) will get merged soon and I don't have to touch sonatype nexus anymore. 

Is it even possible to let bintray sign future versions if I signed previous versions myself? I'd have to give bintray my secret key or the public key would change between versions.

**Comment by raulraja** [comment]
Bintray uses their own keys to sign on your behalf but you can override
them. When you release you will get a notification to approve the release
which then you can click a button to sync from jcenter to Central and it
syncs it in bulk. It's a bit clunky but it works most of the time and it's
fairly fast
