### ISSUE TITLE
1.6.0-RC compatibility

### ISSUE THREAD

**Issue by jameskleeh** [tschuchortdev/kotlin-compile-testing#222]
I'm trying to test compilation with  `1.6.0-RC-1.0.1-RC`, however the constructor for `MessageCollectorBasedKSPLogger` has changed and thus its not compatible with this module. This is a request to get a release that is compatible with 1.6 RC

**Comment by tschuchortdev** [comment]
As you have come to find out yourself, the internal API of the compiler changes frequently between releases, so KCT can only support one compiler version at a time or the maintenance burden would be too great. I can not make a stable release of KCT depending on Kotlin `1.6.0-RC` until `1.6.0` is released for good. Will a `SNAPSHOT` release be okay for you until then?

**Comment by jameskleeh** [comment]
Yeah a snapshot release would be great!

**Comment by ZacSweers** [comment]
This is also broken in KSP 1.5.31-1.0.1, so it's not even specific to Kotlin 1.6.0-RC

> the maintenance burden would be too great

This is an incompatibility with KSP, not kotlinc and resolvable via simple release compiled against the newer version (no source changes needed)

**Comment by martinbonnin** [comment]
Now that 1.6 is released, looks like it should be possible to update? 
Dependabot actually created a PR there: https://github.com/tschuchortdev/kotlin-compile-testing/pull/224 that failed with `ETIMEDOUT` so maybe it's just a matter of restarting it?

**Comment by ZacSweers** [comment]
I made a full PR at #223
