### ISSUE TITLE
Snapshot embedded artifact no longer available

### ISSUE THREAD

**Issue by drewhamilton** [tschuchortdev/kotlin-compile-testing#246]
The main branch depends on the embedded compiler [version 1.6.20-dev-7317](https://github.com/tschuchortdev/kotlin-compile-testing/blob/master/build.gradle#L3), which appears to be no longer available. (See my failed [build message](https://github.com/drewhamilton/Poko/runs/5397031560?check_suite_focus=true).) While the [kotlin-annotation-processing-embeddable artifact directory](https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev/org/jetbrains/kotlin/kotlin-annotation-processing-embeddable/) does not have this version, it does have a 1.6.20-RC version.

I can offer a PR if it's just this one liner change, but I don't know this code base so I'm not sure if you'd expect other side effects/changes needed. What do you think?

**Comment by tschuchortdev** [comment]
Thanks for the heads up. I've made a new pre-release that should fix it.

**Comment by drewhamilton** [comment]
Nice, thanks!
