### ISSUE TITLE
Support for generated source files

### ISSUE THREAD

**Issue by ZacSweers** [tschuchortdev/kotlin-compile-testing#28]
Right now the only files reported in `generatedFiles` are the compiled class files. I have a processor where I'd like to verify the generated source as well to check an expected implementation.

**Comment by tschuchortdev** [comment]
With `generatedFiles` you mean the property of `KotlinCompilation.Result`, right? As for `reportOutputFiles`, that is a compiler argument which I can't change. 

If I understood you correctly, you also want to see the intermediate generated `*.kt` source files, while currently `Result.generatedFiles` only contains the final class files and resources. This should be very easy to do: We gather the files from the `classesDir` so we can simply traverse the `kaptSourceDir` and `kaptKotlinGeneratedDir` as well (should work as long as the AP respects the `kapt.kotlin.generated` argument... I think there have been some changes here recently).  The question is: Should we also include stub files and kapt incremental data?
