### ISSUE TITLE
Cannot compile code with `expect` type

### ISSUE THREAD

**Issue by micHar** [tschuchortdev/kotlin-compile-testing#303]
I'm using your fantastic library to test my multiplatform annotation processor which uses common source code and generates ios source sets. The tests look [sth like this](https://github.com/FutureMind/koru/blob/master/koru-processor/src/jvmTest/kotlin/com/futuremind/koru/processor/TypesGenerationTest.kt#L38).

Now everything works fine until I add `expect` modifier to the test code, e. g. `expect interface InterfaceGenerationExample`. There is a `COMPILATION_ERROR` and the error is `e: /var/folders/8n/.../T/.../sources/interface1.kt: (7, 1): The feature "multi platform projects" is experimental and should be enabled explicitly`.
Right now the tests are run in `jvmTest` sourceSet, but I also tried running them in `commonTest` source set and the result is the same. For both kapt and ksp.

Is there any way to test code with `expect / actual` modifiers?

**Comment by micHar** [comment]
I tried adding `kotlin.mpp.stability.nowarn=true` as per these [recommendations](https://youtrack.jetbrains.com/issue/KTIJ-18408), but I have a feeling that this library compiles in a different context than the source set of the tests. Maybe there's a way to configure its compiler with such flags?

**Comment by tschuchortdev** [comment]
`kotlincArguments = listOf("-Xmulti-platform")` works. I found this through trial and error, since the compiler flags are mostly undocumented. A `KotlinCompilation.multiplatform: Boolean` option will be in the next release.

**Comment by micHar** [comment]
@tschuchortdev I tried it and the result was the same unfortunately (for both kapt and ksp fwiw).

```
KotlinCompilation().apply {
    workingDir = tempDir
    inheritClassPath = true
    sources = sourceFiles
    kotlincArguments = listOf("-Xmulti-platform")
    verbose = false
    when (processorType) {
        ProcessorType.KAPT -> {
            annotationProcessors = listOf(KaptProcessor())
        }
        ProcessorType.KSP -> {
            symbolProcessorProviders = listOf(KoruProcessorProvider())
            kspIncremental = false
        }
    }
```
