### ISSUE TITLE
No way to specify custom kotlin compiler arguments

### ISSUE THREAD

**Issue by ZacSweers** [tschuchortdev/kotlin-compile-testing#34]
Currently it's only possible to set javac args and kapt options, but for custom kotlin compiler plugins there's currently no way to set compiler arguments that they may consume

**Comment by tschuchortdev** [comment]
Is there a way that I can access such a plugin option directly in a `ComponentRegistrar` so I can write a test for it?

**Comment by ZacSweers** [comment]
As in an example? Or are you suggesting just creating a second constructor for tests? I'm doing the latter right now, but would prefer to not have to add test-only APIs in it 🙂

**Comment by tschuchortdev** [comment]
As in example. Adding the appropriate CLI options to the library is no problem. But naturally I would like to test that they actually work, so I need some way to access the CLI options in the `ComponentRegistrar` that is given to the `KotlinCompilation`. I have done some googling and only found an example where the plugin ID is declared in Gradle code and the options are then read in a separate `CommandlineProcessor` class where they are added to the `CompilerConfiguration` which can later be read by the `ComponentRegistrar`. Perhaps it's not enough to be able to pass a `ComponentRegistrar` to the `KotlinCompilation` and other classes necessarily belong to a plugin as well. Would it be useful for you to also pass instances of `CommandlineProcessor` to the `KotlinCompilation`?

**Comment by ZacSweers** [comment]
Here's an example - https://github.com/ZacSweers/redacted-compiler-plugin

A commandlineprocessor could work!
