### ISSUE TITLE
'com.sun.tools.javac.util.Context' class can't be found 

### ISSUE THREAD

**Issue by FrederickKlyk** [tschuchortdev/kotlin-compile-testing#36]
First of all, great lib.
In our Android project, the following error is thrown on Windows machines during the test:

e: [kapt] 'com.sun.tools.javac.util.Context' class can't be found ('tools.jar' is absent in the plugin classpath). Kapt won't work.

java.lang.AssertionError: Expected <OK>, actual <COMPILATION_ERROR>.

However, the test runs correctly on the Unix system.

The correct path is also found running the debugger when "jdkHome? .Let {findToolsJarFromJdk (it)}" is called. The corresponding Context.class can also be found in tools.jar.

ClassNotFoundException is thrown when "Class.forName("com.sun.tools.javac.util.Context")" is called.

My configuration:
> Win10
> Android Studio: 3.5.3
> JDK(Oracle): 1.8.0_241
> JRE(Oracle): 1.8.0_241
> kotlin-compile-testing: 1.2.6
> Kotlin version: 1.3.61

**Comment by tschuchortdev** [comment]
- Does the same problem occur with non-Android projects?
- I assume the tests are run locally (no robolectric) and not instrumented?

**Comment by FrederickKlyk** [comment]
Yes, they are running as JUnit 4 tests locally without roblectric nor as a instrumented test.
The test with my Annotation Processor works in a simple gradle project with IntelliJ

> IntelliJ IDEA 2019.2.4 (Community Edition)
> Build #IC-192.7142.36, built on October 29, 2019
> Runtime version: 11.0.4+10-b304.77 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by tschuchortdev** [comment]
I can't seem to reproduce this issue. When I run a compile test with annotation processor inside a java library module in an android project (in android studio) it works fine. And calling the compile testing library from within an android module doesn't work at all because `javax.annotation.processing.AbstractProcessor` is not available.

**Comment by FrederickKlyk** [comment]
Hey,

sorry for late response. 
I tried the same code aswell as a minimalistic simple example in another Android project (within annotaion processor inside a java lib module), and it works.
In my actual project, at least the minimalistic simple example failed with the above mentioned exception.

Seems to be a problem with another lib/configuration. I will reply, when I found new evidence.

**Comment by FrederickKlyk** [comment]
Hey,

sorry for late response.
I tried the same code aswell as a minimalistic simple example in another Android project (within annotaion processor inside a java lib module), and it worked.
In my actual project, even the minimal example doesn't work and failed with the above mentioned exception.

Seems to be a problem with another lib/configuration. I will reply, when I found new evidence.

**Comment by FrederickKlyk** [comment]
Hey,

sorry for the late response.
I tried the same code aswell as a minimalistic simple example in another Android project (within annotaion processor inside a java lib module), and it worked.
In my actual project, even the minimal example doesn't work and failed with the above mentioned exception.

Seems to be a problem with another lib/configuration. I will reply, when I found new evidence.

**Comment by tschuchortdev** [comment]
Okay, keep me updated. Some ideas/hints for you:

- There might be a problem with the load order. Perhaps more than one tools.jar is on the plugin classpath
- Is there a transitive dependency conflict on `kotlin-compiler-embeddable`?
- Check the classloader used by Kapt

**Comment by dumbfingers** [comment]
Hi @tschuchortdev @FrederickKlyk,
Recently I've met this problem again during Android Espresso build. This only happens on Microsoft DevOps (CI) but not on my local machine, MacOS.

Local Configuration(MacOS)
kotlin: 1.4.30
kotlin-gradle-plugin: 1.4.30
Android Studio 2020.3.1 Canary 11
JDK-8
gradle-6.8.2

I believe on the DevOps CI, it uses same gradle version and also on JDK 8.

**Comment by sofronovic** [comment]
@dumbfingers Hi, I am facing the same issues on Azure DevOps, do you have any update on this one?

**Comment by dumbfingers** [comment]
@sofronovic 
Sorry, but I'm still experiencing this issue 🤷  
Have you tried it on a local Windows machine to see if this persists?

**Comment by sofronovic** [comment]
@dumbfingers Works on my machine (windows)

**Comment by dumbfingers** [comment]
@sofronovic then this might be an issue on DevOps.

**Comment by sebastienrieu** [comment]
> @dumbfingers Hi, I am facing the same issues on Azure DevOps, do you have any update on this one?
for me too ! same problem since Monday on AzureDevops only, it worked well last week.

**Comment by sebastienrieu** [comment]
@dumbfingers how can we know when azuredevops will fix this issue ? or how to signal it ?

**Comment by jayalodha** [comment]
I am also facing the same issue on azure devops right now.

**Comment by tomklecha-is** [comment]
same here - since yesterday all our CI builds are failing on the same reason

**Comment by dumbfingers** [comment]
@sebastienrieu @jayalodha @tomklecha-is 
I think this issue in DevOps is just a coincidences with this lib `kotlin-compile-testing`. So we'd better stop posting here as it is not related to this repo.

I've got the reply from DevOps:

>Hi There, Thanks for writing to us! Sorry for the inconvenience! We have a couple of other users reporting this same issue and we are currently investigating. We will keep you posted!

We could all report this by:
https://github.com/microsoft/appcenter/issues/new/choose

Then choose "Bugs and support requests" and select your related app, then on top right, click "?" then "Contact Support"

**Comment by jayalodha** [comment]
Try using this  pool: vmImage: 'windows-latest' instead of mac-os .
This has fixed issue on my end on windows machine

**Comment by sofronovic** [comment]
@jayalodha works for me also

**Comment by sebastienrieu** [comment]
Issue is here : https://developercommunity.visualstudio.com/t/Android-Pipelines-with-kapt-are-failing-/1380366

**Comment by sebastienrieu** [comment]
it seems to be OK now without changing nothing.
