### ISSUE TITLE
Support Kotlin 1.8.21

### ISSUE THREAD

**Issue by dariuszkuc** [tschuchortdev/kotlin-compile-testing#379]
Hello 👋 

Awesome work on the library! By any chance there will be a new version released soon that supports Kotlin v1.8.21? 

I tried updating it ([link](https://github.com/dariuszkuc/kotlin-compile-testing/commit/c6f8742aa4c8a3c79b6b5f32eaf0a1185efdb855)) but sadly there is some change in behavior in v1.8.20 that breaks JS compiler. Nothing jumps out from the [release notes](https://kotlinlang.org/docs/whatsnew1820.html) - they did add alpha support for new JS IR compiler but that "shouldn't" affect the legacy compiler.

After updating to v1.8.20+ JS compilation fails asking to set some IR properties (`-ir-output-dir` and `-ir-output-name`). I tried updating the default [`KotlinJsCompilation#jsArgs()`](https://github.com/tschuchortdev/kotlin-compile-testing/blob/master/core/src/main/kotlin/com/tschuchort/compiletesting/KotlinJsCompilation.kt#L75-L95) args to include those but that didn't work either, i.e. I added the following

```kotlin
args.moduleName = "KCT"
args.outputDir = outputDir.toString()
```

With the above JS compilation runs but does not produce any outputs.... Any help would be appreciated!

**Comment by tschuchortdev** [comment]
I'm glad to hear that you like it. In cases like this, I find it often helps to grep the Kotlin repository to look for any changes that suggest how to use the new options. 

> With the above JS compilation runs but does not produce any outputs

With that change are your tests failing or are they green? In the linked PR, all tests are green and they seem to do some rudimentary tests for the contents of the generated JS file.

**Comment by dariuszkuc** [comment]
> With that change are your tests failing or are they green? In the linked PR, all tests are green and they seem to do some rudimentary tests for the contents of the generated JS file.

Tests were failing on my machine - there were no generated JS files so assertions were failing. I did not remove the `args.outputFile` so maybe that was it. Thanks for taking a look!
