### ISSUE TITLE
Running in Android project

### ISSUE THREAD

**Issue by malvinstn** [tschuchortdev/kotlin-compile-testing#5]
Do I need to supply extra parameters for this to run on an Android project? This is what I'm doing:

```kotlin
val result = KotlinCompilation().apply {
    sources = listOf(
        SourceFile.new(
            "Person.kt",
            """
            import com.malvinstn.annotation.AutoMap

            @AutoMap
            data class Person(
                val id: Long,
                val name: String?
            )
        """
        )
    )
    annotationProcessors = listOf(AutoMapProcessor())
    inheritClassPath = true
    messageOutputStream = System.out
}.compile()
assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode)

val kClazz = result.classLoader.loadClass("PersonKt")
```

But trying to load `PersonKt`, which is a class that should have been generated from `AutoMapProcessor`, will throw:
```
java.lang.ClassNotFoundException: PersonKt
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.malvinstn.processor.Processor2Test.testSample(Processor2Test.kt:32)...
```

Seems like my `AutoMapProcessor` was not run at all?
I'm using Kotlin 1.3.41

**Comment by tschuchortdev** [comment]
> Do I need to supply extra parameters for this to run on an Android project?

Not that I know of. Are you by any chance using MacOS? There is another issue (#4) where the annotation processor apparently isn't run on MacOS. I don't have a Mac so I can only personally test on Windows and Linux.

Please post the output of compilation with `verbose=true`.

If the annotation processor is run it should print the names of all files that are generated. Perhaps you forgot the the package name in `loadClass("PersonKt")`?

> I'm using Kotlin 1.3.41

The library doesn't use the system Kotlin compiler but a bundled one, which is still on 1.3.21. So if you use any language features that were added after 1.3.21 it won't work. Unfortunately the library depends on compiler internals that don't have a stable API and break constantly, so updating it isn't always easy, but I will release 1.3.41 soon.

**Comment by tschuchortdev** [comment]
@malvinstn I have released a new version with an important bug fix and updated bundled compiler. Please see if this resolves your issue.

**Comment by malvinstn** [comment]
Thanks! I don't have my pc with me right now, I'll let you know once I'm able to test.
Cheers!

**Comment by malvinstn** [comment]
Hi, I've just tested it with the latest 1.2.0 and it works perfectly for my case. Thank you so much!
