### ISSUE TITLE
Jitpack fails to install project

### ISSUE THREAD

**Issue by tschuchortdev** [tschuchortdev/kotlin-compile-testing#64]
Jitpack is unable to release artifacts because the install task is missing:

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' not found in project ':ksp'.
```

**Comment by F43nd1r** [comment]
Jitpack builds are failing:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:signMavenJavaPublication'.
> Cannot perform signing task ':core:signMavenJavaPublication' because it has no configured signatory
```

**Comment by tschuchortdev** [comment]
Hi @F43nd1r. Since the snapshots now get uploaded to Sonatype Nexus as well, there is no reason to use jitpack anymore and I no longer support it. Please use Maven Central instead.

**Comment by F43nd1r** [comment]
I'm using jitpack to access snapshot versions, because there is no release for ksp alpha 10 yet.

**Comment by tschuchortdev** [comment]
The snapshots are now also uploaded to Sonatype and you no longer need jitpack: 
https://oss.sonatype.org/service/local/repositories/snapshots/content/com/github/tschuchortdev/kotlin-compile-testing-ksp/1.4.1-SNAPSHOT/kotlin-compile-testing-ksp-1.4.1-20210518.080004-8.pom
But the URL for the snapshot repository is different from the release repository, so you will need to add the snapshot repository URL to your gradle file. Probably something like this:
```
repositories {
  maven {
    https://oss.sonatype.org/content/repositories/snapshots
  }
}
```
