### ISSUE TITLE
Kotlin 1.4.20

### ISSUE THREAD

**Issue by jimirocks** [tschuchortdev/kotlin-compile-testing#78]
The library seems not to work with kotlin 1.4.20, however working smooth when
```
testRuntimeOnly("org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.21")
testRuntimeOnly("org.jetbrains.kotlin:kotlin-annotation-processing-embeddable:1.4.21")
```

is added to buildscript. If this is the only thing to do to upgrade, I will be happy to create PR.

**Comment by tschuchortdev** [comment]
I have updated the Kotlin version to 1.4.21 in version 1.3.3. You should be able to use it now. If it doesn't work for some reason, please report back.
